### ISSUE TITLE
Unable to resolve action / unable to find version 

### ISSUE THREAD

**Issue by f-rakete** [kbrashears5/github-action-auto-accept-collabs#5]
I've been trying to get this up and running, but I might be too stupid, can you help me out? 

I've set it up like this:
![image](https://github.com/kbrashears5/github-action-auto-accept-collabs/assets/69428398/cc353469-9a3c-463a-a4c1-92f9f8eeb9d4)
have a token stored in secrets / actions 
![image](https://github.com/kbrashears5/github-action-auto-accept-collabs/assets/69428398/82e0e598-ff98-4a7b-b325-db97168c1a1f)
Key has the following scopes:
![image](https://github.com/kbrashears5/github-action-auto-accept-collabs/assets/69428398/d7611743-2221-4049-8667-4d89bda96328)

but it fails with 
![image](https://github.com/kbrashears5/github-action-auto-accept-collabs/assets/69428398/9ca2423f-f80e-418c-9cae-c8c6671ded33)

doesn't matter if i pick version 1.0.0 or 1.0.1, as suggested in one of the issue posts. #3 

can you help me out? thanks! (maybe @roblanf has some ideas?)

**Comment by kbrashears5** [comment]
I've published a new version to help with latest tags, use `v2.0.0`

**Comment by f-rakete** [comment]
seems to work now - thanks a lot 👍
